### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by josearareis** [dabear/NightscoutShareServer#10]
SÓ DA ESSE ERRO 
Oops - Nightscout is having trouble
Don't panic, we can work this out! This happens to the best of us.

Check the errors below and then refer to the troubleshooting documentation.

Errors occurred during startup:
Unable to connect to Mongo
MONGODB_URI seems invalid: Invalid connection string

**Comment by dabear** [comment]
project is not active. fix it yourself :)
