### ISSUE TITLE
Add Calibration Data 

### ISSUE THREAD

**Issue by natetr** [dabear/NightscoutShareServer#3]
The other day there was an issue in Loop about data being skewed when the calibration changes the BG numbers dramatically. Pete mentioned that the calibration data should be imported into Loop from wherever the CGM data is coming from, so Loop would make proper adjustments. I believe Dexcom is doing this and I know iosxdripreader uploads this data to Nightscout. Is it possible to incorporate the calibration into nightscoutshareserver?

**Comment by dabear** [comment]
Hi there. I am not certain what you are asking. Nightscoutshareserver uses
the glucose values stored in nightscout. While I do know that dexcom also
uploads raw glucose values and calibration data, these extra data are very
dexcom specific. I mainly use the libre myself which do not upload
calibration data. I wanna keep nightscoutshareserver sensor agnostic.

**Comment by natetr** [comment]
That makes sense. This is the thread I am referencing. https://github.com/LoopKit/Loop/issues/670

I didn't know if it was something that was simple to do or if it would make sense.
