### ISSUE TITLE
Nightscout URL issue

### ISSUE THREAD

**Issue by getek-nightscout** [dabear/NightscoutShareServer#5]
Hi, I'm trying to setup NS share server and I've got an issue with Nightscout URL. I've tried typing addresses with http, https, without it, ending with "/" and without it. I've also tried entering URL's for different versions of NS sites. Each time when I hit "Load glucose" button site responds with "Could not retrieve glucose data, please verify your nightscout url:  error, Internal Server Error".

**Comment by dabear** [comment]
Show me your nightscoutshareserver site? PM me on gitter if you don't want to paste it here.
Also, if you're using iphone and loop, you should probably consider spike, which can fetch glucose from nightscout and feed it directly into loop.

https://spike-app.com/

**Comment by getek-nightscout** [comment]
My site: https://hubidexcom.azurewebsites.net/
My log_secret: Thisisatestpass

**Comment by dabear** [comment]
Are you using a special build of cgm-in-the-cloud? 

Your site is having problems decoding glucose entries. It expects glucose datestring from nightscout to be in the format "2018-06-28T12:17:15.426+0200", but yours is in another format:  "Thu Jun 28 12:13:32 CEST 2018."

I've created a workaround, just update your build; https://github.com/dabear/NightscoutShareServer/commit/8e06f9c30e91a8922050fd0b69fe78f37cffd9f3

**Comment by getek-nightscout** [comment]
Thank's a lot! Works like a charm 👍 
I wasn't using any special build. I've tested many more NS urls from Polish users and none of them returned proper BG. Could it be Azure location (set to North Europe) or Polish time zone in NS profile settings?

**Comment by dabear** [comment]
Most likely a timezones issue
