### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by matti05** [dabear/NightscoutShareServer#6]
Hi, I moved my NS website to Heroku. NS Share Server works like a charm with Azure<>Heroku combination. Despite that I would like to move my NS Share Server to Heroku. I tried to deploy this, but it doesn't work. 

> No default language could be detected for this app.
>  			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically. 
> 			See https://devcenter.heroku.com/articles/buildpacks

Have you ever tried to deploy NS Share Server to Heroku?

**Comment by dabear** [comment]
Cannot be done, heroku is not supported for traditional .net deployments

**Comment by dabear** [comment]
I have a version of nightscoutshareserver working on heroku now. It's a rewrite. Please try it out, but it requires you to install some tools on your computer to compile and upload as a docker container to heroku.

Please follow these steps, you may need to install any of these tools first.
```
git clone https://github.com/dabear/NightscoutShareServer.git
cd NightscoutShareServer/NightscoutShareServer
git checkout dotnetcore

docker build -t yournameshareserver ./bin/Release/netcoreapp2.1/publish/

heroku login
heroku container:login
heroku create yournameshareserver

docker tag yournameshareserver registry.heroku.com/yournameshareserver/web

docker push registry.heroku.com/yournameshareserver/web


heroku config:set -a yournameshareserver NS_Host="https://yournightscoutsite.herokuapp.com" Enable_Mocked_Mode="false" 
heroku container:release web -a yournameshareserver

Then navigate to https://yournameshareserver.herokuapp.com

```

**Comment by dabear** [comment]
Please see the main readme file. Heroku is now supported. https://github.com/dabear/NightscoutShareServer/blob/master/README.md

**Comment by Piotras625** [comment]
Hi can you please help me with installation Nnightscoutshareserver? I do not understand how to read this 
git clone https://github.com/dabear/NightscoutShareServer.git
cd NightscoutShareServer/NightscoutShareServer
git checkout dotnetcore
